# Generated by Django 4.2 on 2023-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='fr_name',
        ),
        migrations.AddField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
