# Generated by Django 4.2 on 2024-02-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_nationality_profile_reg_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tel',
        ),
    ]
