# Generated by Django 4.2 on 2024-04-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_onsite',
            field=models.BooleanField(default=False),
        ),
    ]
