# Generated by Django 4.2 on 2024-04-20 21:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_timing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('movement', models.CharField(blank=True, choices=[('entry', 'Entrée'), ('exit', 'Sortie')], max_length=10, null=True)),
                ('user_password', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
