# Generated by Django 4.2 on 2024-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_timemanagement_delete_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_alt',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
