# Generated by Django 4.2 on 2024-02-27 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_delete_chatnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
