# Generated by Django 4.2 on 2024-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_remove_chatmessage_thread_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
