# Generated by Django 4.2 on 2024-03-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0013_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
