# Generated by Django 4.1.7 on 2023-04-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appointment_arrived_at_appointment_departed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
