# Generated by Django 4.1.7 on 2023-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='visit',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
