# Generated by Django 4.1.7 on 2023-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_appointment_signature_alter_visit_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_num',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='doc_num',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
