# Generated by Django 4.1.7 on 2023-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_appointment_doc_num_visit_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
