# Generated by Django 4.1.7 on 2023-04-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_visit_time_alter_visit_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='visit_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_count',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='visit',
            name='guest_count',
            field=models.IntegerField(default='1'),
        ),
    ]
