# Generated by Django 4.1.7 on 2023-04-23 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_visit_types_appointment_guest_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date',
        ),
    ]
