# Generated by Django 4.1.7 on 2023-04-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_visit_guest_count_remove_visit_signature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='signature',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nationality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
