# Generated by Django 4.1.7 on 2023-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_appointment_guest_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='arrived_at',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='departed_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
