# Generated by Django 4.1.7 on 2023-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_visit_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='civility',
            field=models.CharField(blank=True, choices=[('Mr.', 'M.'), ('Mrs.', 'Mme.'), ('Miss.', 'Mlle.')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='civility',
            field=models.CharField(blank=True, choices=[('Mr.', 'M.'), ('Mrs.', 'Mme.'), ('Miss.', 'Mlle.')], default='', max_length=50, null=True),
        ),
    ]
