# Generated by Django 4.2 on 2023-05-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_visit_context_alter_appointment_civility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='doc_num',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='tel',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
