# Generated by Django 4.2 on 2024-02-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_status_visit_accepted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='status',
        ),
    ]
