# Generated by Django 4.2 on 2024-02-13 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_appointment_status_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='visit',
            name='context',
            field=models.CharField(blank=True, choices=[('friendly', 'Amicale'), ('familial', 'Familiale'), ('professional', 'Professionelle')], default='professionelle', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
    ]
