# Generated by Django 4.2 on 2024-02-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_appointment_gender_remove_visit_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='visit',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
