# Generated by Django 4.2 on 2024-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_appointment_qr_code_appointment_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
