# Generated by Django 4.2 on 2024-03-02 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_appointment_signature_alter_visit_signature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='guest',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='doc_num',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='guest',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='civility',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id_doc',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='civility',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='doc_num',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='id_doc',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='tel',
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_document',
            field=models.CharField(blank=True, choices=[('id_card', "Carte Nationale d'Identité (CNI)"), ('consul_card', 'Carte Consulaire'), (
                'ecowas_card', 'Carte CEDEAO'), ('driver_license', 'Permit de conduire'), ('passport', 'Passport international')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='signature_in',
            field=models.ImageField(
                blank=True, null=True, upload_to='signatures/in/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='signature_out',
            field=models.ImageField(
                blank=True, null=True, upload_to='signatures/out/'),
        ),
        migrations.AddField(
            model_name='visit',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='id_document',
            field=models.CharField(blank=True, choices=[('id_card', "Carte Nationale d'Identité (CNI)"), ('consul_card', 'Carte Consulaire'), (
                'ecowas_card', 'Carte CEDEAO'), ('driver_license', 'Permit de conduire'), ('passport', 'Passport international')], default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='id_number',
            field=models.CharField(default=1233, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='signature_in',
            field=models.ImageField(
                blank=True, null=True, upload_to='signatures/in/'),
        ),
        migrations.AddField(
            model_name='visit',
            name='signature_out',
            field=models.ImageField(
                blank=True, null=True, upload_to='signatures/out/'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='arrived_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
