# Generated by Django 4.2 on 2024-03-03 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_guest_appointment_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='signature_in',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='signature_out',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='signature_in',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='signature_out',
        ),
        migrations.AddField(
            model_name='appointment',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='visit',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='arrived_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_document',
            field=models.CharField(choices=[('id_card', "Carte Nationale d'Identité (CNI)"), ('consul_card', 'Carte Consulaire'), ('ecowas_card', 'Carte CEDEAO'), ('driver_license', 'Permit de conduire'), ('passport', 'Passport international')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_number',
            field=models.CharField(default='id_card', max_length=50),
            preserve_default=False,
        ),
    ]
