# Generated by Django 4.2 on 2024-03-06 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_appointment_signature_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='id_document',
            field=models.CharField(blank=True, choices=[('id_card', "Carte Nationale d'Identité (CNI)"), ('consul_card', 'Carte Consulaire'), ('ecowas_card', 'Carte CEDEAO'), ('driver_license', 'Permit de conduire'), ('passport', 'Passport international')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(default='lastname', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sex',
            field=models.CharField(choices=[('female', 'Feminin'), ('male', 'Masculin')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visit',
            name='context',
            field=models.CharField(choices=[('friendly', 'Amicale'), ('familial', 'Familiale'), ('professional', 'Professionelle')], default='professionelle', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id_document',
            field=models.CharField(choices=[('id_card', "Carte Nationale d'Identité (CNI)"), ('consul_card', 'Carte Consulaire'), ('ecowas_card', 'Carte CEDEAO'), ('driver_license', 'Permit de conduire'), ('passport', 'Passport international')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='last_name',
            field=models.CharField(default='lastname', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visit',
            name='sex',
            field=models.CharField(choices=[('female', 'Feminin'), ('male', 'Masculin')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
