# Generated by Django 4.2 on 2024-03-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0035_appointment_observations_visit_observations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='departed_at',
            field=models.TimeField(blank=True, default='', null=True),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('SARL', 'SARL'), ('SARLU', 'SARLU')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('employees', models.ManyToManyField(related_name='companies', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
