# Generated by Django 4.2 on 2024-03-09 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0036_alter_visit_departed_at_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='companies', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
