# Generated by Django 4.2 on 2024-03-09 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_company_timestamp_notification_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='arrived_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='ended_at',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='departed_at',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='departed_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
