# Generated by Django 4.2 on 2024-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_rename_arrived_at_appointment_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_missed',
            field=models.BooleanField(default=False),
        ),
    ]
