# Generated by Django 4.2 on 2024-03-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_visit_is_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='departed_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ended_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
