# Generated by Django 4.2 on 2024-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_appointment_is_cancelled_appointment_is_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
