# Generated by Django 4.2 on 2024-04-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_workdays_company_ending_hour_company_starting_hour_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkDays',
            new_name='WorkDay',
        ),
    ]
