# Generated by Django 4.2 on 2024-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_workdays_workday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='ending_hour',
        ),
        migrations.RemoveField(
            model_name='company',
            name='starting_hour',
        ),
        migrations.AddField(
            model_name='company',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
