# Generated by Django 4.2 on 2024-04-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_remove_company_ending_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
