# Generated by Django 4.2 on 2024-04-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_rename_n_type_notification_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
