# Generated by Django 4.2 on 2024-04-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_appointment_is_finished_visit_is_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='accepted_at',
            new_name='started_at',
        ),
        migrations.AddField(
            model_name='visit',
            name='ended_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
