# Generated by Django 4.2 on 2024-06-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_workday_closing_time_workday_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notice',
            field=models.CharField(blank=True, choices=[('new_user', 'new_user'), ('new_visit', 'new_visit'), ('new_appt', 'new_appt'), ('new_chat', 'new_chat'), ('updated_visit', 'updated_visit'), ('updated_appt', 'updated_appt'), ('updated_user', 'updated_user')], max_length=50, null=True),
        ),
    ]
